version: '3.7'

services:
  n8n:
    image: n8nio/n8n
    restart: unless-stopped
    ports:
      - '5678:5678'
    environment:
      # n8nのタイムゾーン設定
      GENERIC_TIMEZONE: Asia/Tokyo
    volumes:
      - ~/.n8n:/home/node/.n8n
